#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: parkTest
#
spring:
  data:
    mongodb:
      uri: mongodb+srv://my_atlas_user:fpemffj159357@cluster0.riaea.mongodb.net/chat
